# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import shortener.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20170611_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bharrurl',
            name='url',
            field=models.CharField(max_length=225, validators=[shortener.validators.validate_url]),
        ),
    ]
